### ISSUE TITLE
Add environmental data to header matrix? +edits. #114

### ISSUE THREAD

**Issue by fmsabatini** [fmsabatini/sPlotOpen_Manuscript#120]
#114 

>  lgzrf commented 10 hours ago

> I have also made a few minor edits to this section, but mainly I have comments and I am not sure how to include them in this system, so I am adding them here:

>    Given that we describe how we used climate and other environmental data to stratify the plot selection, it seems odd not to add those data to the header matrix. Perhaps those data cannot be shared in this way? If so then it may be worth mentioning that? Anyway, I thought I would suggest this in case it is feasible.
>    Where it says "Functional trait information was available for 20,932 species", was this before or after gap-filling?
>    Some of the references are blank in Table 2. I guess that is because there is no publication associated with some of the datasets? I suggest explaining this in the paragraph that talks about the object 'references'.
>    I also suggest explaining somewhere in this section that a releve is another word for a vegetation plot (not everyone will know this).

**Comment by fmsabatini** [comment]
@lenjon wrote in Issue: https://github.com/fmsabatini/sPlotOpen_Manuscript/issues/106
>By the way, shall we also provide the pca3.RData object for free together
with the code you wrote to generate that figure? That would be nice too :)

>I also wonder if we could make an additional panel (or standalone figure)
to display the spatial projection of PCA1 and PCA2, just that people have a
sense of the meaning of these two PCA axes. What do you think?

**Comment by fmsabatini** [comment]
We discussed the issue whether providing the environmental data, and we are inclined not to do so.
@lgzrf 
Even if data from CHELSA and SOILGRIDS are shared under CC0, which would allow us to do so, these data are evolving over time, and providing a screenshot of these data would influence the users of sPlotOpen to stick to this outdated environmental data. This is relevant, since the whole resampling procedure was done 3 years ago, and both CHELSA and SOILGRIDS have been updated since then.

**Comment by fmsabatini** [comment]
@lenjon, sure we could provide the PC1-PC2 values for each plot. But then we will also need to report enough data to allow the users to interpret these axes, I'm talking about the loadings and\or correlations b\w each variable and each PC, for instance using a biplot. Together with the graphs of the spatial distribution of PC1-PC2 values, wouldn't this end up taking too much space?

Data papers in GEB are limited to 2000 words (I have no idea where we stand, currently) and 2 Figures. Maybe the solution is to make a dedicated appendix only for PCA. Appendices are not allowed by Scientific data. I think they are in GEB, but I'm not 100% sure.

**Comment by fmsabatini** [comment]
Check this out
@lengyelat @lenjon
For the appendix on PCA
![figure4](https://user-images.githubusercontent.com/51127026/101527626-8980f000-398e-11eb-8746-fae2639e3951.png)

**Comment by lenjon** [comment]
Hi Francesco,

This figure with the two maps of the PC1 and PC2 axes is perfect and can
indeed go in the appendices together with a biplot to show the laodings and
correlations of the 30 variables along both PC1 and PC2, also mentioning
briefly the amount of variance captrured by each of the two PC axes. This
together with the two maps should be fair enough for the curious reader who
would like to use our PCA outputs. Thus, in addition to providing the R
code to run the PCA and prepare the raster layers of the two PCA axes (+
code of your very nice figures to display it), we could also provide the
data for PC1 and PC2, basically the two global raster layers. I think it is
a very nice and complementary addition to sPlotOpen and actually part of it
since this is background environmental space to build sPlotOpen. Thus, it
would make sense to provide this data layers (PC1 + PC2 grids) too to the
user. Besides, this is also our own product and if we do not provide teh
raw data to generate PC1 and PC2 (these data are free and available) we are
at least providing out own product to then represent sPlotOpen within its
sampling design space :) I could see people using sPlotOpen and wanting to
display the data within the PC1-PC2 space :) I think this is super useful.

Best,

Jonathan

Jonathan Lenoir
Chargé de Recherche CNRS

Université de Picardie Jules Verne
Ecologie et Dynamiques des Systèmes Anthropisés
UMR 7058 CNRS-UPJV
1 Rue des Louvels
80000 AMIENS
FRANCE

http://www.u-picardie.fr/edysan/_listing-personnel/jonathan-lenoir/
http://scholar.google.com/citations?user=Xx5
<http://scholar.google.com/citations?user=Xx52nH4AAAAJ>2nH4AAAAJ
<http://scholar.google.com/citations?user=Xx52nH4AAAAJ>
http://www.researchgate.net/profile/Jonathan_Lenoir/
http://jonathanlenoir.wordpress.com/

**Comment by lengyelat** [comment]
I agree, this is a very informative pair of maps.

**Comment by fmsabatini** [comment]
The values of the PC1-PC2 are not part of the header file.
