### ISSUE TITLE
Aggregating taxonomic ranks lower than species at species level

### ISSUE THREAD

**Issue by fmsabatini** [fmsabatini/sPlotOpen_Manuscript#125]
lgzrf commented 9 hours ago in PR https://github.com/fmsabatini/sPlotOpen_Manuscript/pull/118

>"All taxa originally denoted at taxonomic ranks lower than species were aggregated at species level." How was this aggregation done? For example, if an average value taken, was it the mean or median? Should be explained.

**Comment by Petr-Petrik** [comment]
I cannot imagine some aggregation by using mathematical formulas :) In our paper (DOI: 10.23855/preslia.2019.001), we use this approach: Taxa distinguished in the national checklist at lower taxonomic ranks (subspecies, variety and form; n = 95) or higher ranks (aggregates and groups; n = 28). Of these, either only a taxon at a higher rank (usually a species) is recorded instead of its type subspecies or variety, which is the only subspecies present in the Czech flora (e.g. Alnus incana was recorded instead of A. incana subsp. incana), or the distribution of a taxon at the respective rank is unknown.

**Comment by fmsabatini** [comment]
It's much simpler than that. Clearly we have no accurate checklist of the subspecies or varieties in all regions of the world. We therefore preferred to identify taxa exclusively at the species level.
e.g., all subspecies of [Carex alpina ](http://www.theplantlist.org/tpl1.1/search?q=carex+alpina) were merge at the level of C. alpina.

@lgzrf maybe 'aggregated' is not the right word here?

**Comment by fmsabatini** [comment]
Rephrased 
https://github.com/fmsabatini/sPlotOpen_Manuscript/blame/master/content/60.TechnicalValidation.md#L14
>The final backone only retained matched taxonomic names at the rank of species or higher.
