### ISSUE TITLE
Table 2 - Various issues

### ISSUE THREAD

**Issue by fmsabatini** [fmsabatini/sPlotOpen_Manuscript#147]
arnste commented 16 hours ago in PR https://github.com/fmsabatini/sPlotOpen_Manuscript/pull/142

> Should aspect be limited to 1 - 360 (as technically 0 and 360 are the same)?

**Comment by Petr-Petrik** [comment]
In fact, this issue concerns table 2, not table 1. However, using definition in ArcGIS it is OK: ["It is measured clockwise in degrees from 0 (due north) to 360 (again due north), coming full circle."](https://desktop.arcgis.com/en/arcmap/10.3/tools/spatial-analyst-toolbox/how-aspect-works.htm)

I have another 4 comments to the table 2:

1. Regarding "Herbs_identified". Does the statement "FALSE = 4876" mean that identification of a taxon was possible only on the level of genus? If yes, it should be explicitly stated. 

2. The abbreviation "ESY" should be referred as "EUNIS habitat classi􀃕cation" to be clear.

3. The term "cryptogams" includes mosses, lichens etc and may be confusing if we refer: "It only contains the species composition of vascular plants, while information on the composition of bryophytes and lichens was discarded since it was only available for a minority of plots". 

4. We use the term "relevé" only in the variable names and the term "record" both for plants and vegetation plots. I suggest to use "Nr. of relevés/vegetation plots" instead of the "Nr. of records". 

Regarding table 1:

1. I suggest to exclude the column with deputy custodians (it is rather fluctuating) and add the column with the percentage of the relevés of the distinct datasets used for sPlot open. We will see than how much data was resampled in a given region.

**Comment by fmsabatini** [comment]
Aspect range corrected in commit https://github.com/fmsabatini/sPlotOpen_Manuscript/commit/9a9c5dc53b9a99a773d863728aaf7450b0c6f80b

**Comment by fmsabatini** [comment]
1. The field Herbs_identified was used to state whether a plot had only information on trees, or also herbs. This field is not reported anymore, since, after standardization, became redundant with 'plants_recorded'
2. This is now explained at https://github.com/fmsabatini/sPlotOpen_Manuscript/blame/master/content/50.DatabaseOrganization.md#L6 and at https://github.com/fmsabatini/sPlotOpen_Manuscript/blame/master/content/91.ManubotTables.md#L119
3. Changed accordingly.
4. Changed to: "Nr. plots with information"

With regards to table 1 - I'm not in favour of deleting the column deputy custodians. Custodians and email addresses change, and this provides redundancy, in case a user doesn't manage to get in touch with the custodian. The same is true for the number of plots in a dataset. The paper is based on sPlot v2.1, so that if we provide the number of plots from that version of sPlot, they would be already outdated, since in many cases the datasets expanded in sPlot 3.0. I prefer to keep it as it is.
