### ISSUE TITLE
Whittaker plot

### ISSUE THREAD

**Issue by florianjansen** [fmsabatini/sPlotOpen_Manuscript#50]
I like this plot very much! And do you see also the grashopper in all these black dots?
However, what about the obvious need to extend the precipitation range of Boreal forest and Temperature rain forest?
I suggest to add at least gray extension areas.

**Comment by fmsabatini** [comment]
The plot comes from a ggplot package. The background colors were digitized by @valentinitnelav as documented here:
https://github.com/valentinitnelav/plotbiomes
Personally, I have no idea how to expand the background there, and I have the impression it would take quite some work.

**Comment by florianjansen** [comment]
library(plotbiomes)
whittaker_base_plot

shows that the plot coordinates are stored in an package object called
Whittaker_biomes

which is a straightforward table:
'
       temp_c precp_cm biome_id  biome
 1   -10.21600 1.607134        6 Tundra
 1.1 -10.62857 1.696938        6 Tundra
 1.2 -11.14116 1.846052        6 Tundra
 1.3 -11.61776 2.028094        6 Tundra
 1.4 -12.05961 2.242129        6 Tundra
 1.5 -12.46799 2.486286        6 Tundra
'
and could be adapted. However, we should discuss this issue first regarding content. Afterwards we can discuss technical issues.

**Comment by fmsabatini** [comment]
That's exactly what I meant with 'quite some work'. Defining and implementing (more or less manually) new polygons.
Whittaker's scheme is more or less accepted  and universally recognized. Unless there's an improved version which is equally accepted, I don't see the point of changing it ourselves and creating new, somewhat arbitrary polygons that we will then need to justify. There might be some better schemes than Whittaker to use, but I don't see the point of investing much time for turning these into a graph, if they are not already implemented somewhere. In other words, it's not a priority, in my view, to implement such a scheme, as I don't think it is so crucial for the paper to expand the background so that all plots are covered. 

Having said that. I might consider alternative solutions, if served on a silver platter :-)

**Comment by Rusina-S** [comment]
Not exactly about the previous discussion about the  but still complementary to it: biome names differ between Figure 2 and Table 2. Should not they be the same? Or some reference should be given in Table 2?  Biome names of Table 2 are used in the text but the reference is given to Fig.2, where reader cannot directly locate biomes 'temperate midlatitudes' and 'subtropics with winter rain'. 
https://github.com/fmsabatini/sPlotOpen_Manuscript/blame/master/content/04.DataRecords.md#L12

**Comment by fmsabatini** [comment]
https://github.com/fmsabatini/sPlotOpen_Manuscript/blame/master/content/04.DataRecords.md#L12
The reference to the Whittaked biomes comes out of blue, according to @Greforb

**Comment by fmsabatini** [comment]
To avoid using two different biome definitions (sBiomes vs Whittaker), I avoid referring to the former in the text 
https://github.com/fmsabatini/sPlotOpen_Manuscript/commit/b72a63a337bbc010f60f3ae6b47c43e1833ca2dd#diff-306266762f83af44bb982febe1822953630d4181e9385a3d83a47be2ce1a8afb

**Comment by fmsabatini** [comment]
jewald472 commented 2 days ago in PR https://github.com/fmsabatini/sPlotOpen_Manuscript/pull/140

> Are Whittaker biomes the best choice for Figure 2, when so many plots (temperate-montane and alpine?) are way outside of their climatic domain? A frequency distribution of plots across biomes would certainly be important (cf. variable Biome in Table 2).

**Comment by fmsabatini** [comment]
We discussed the issue with @lenjon and @hbruelheide and decided to show two graphs next to each other:
The Whittaker biomes and the equivalent graph showing the classification of biomes used in sPlotOpen.
This is now Figure 2
https://fmsabatini.github.io/sPlotOpen_Manuscript/#fig:Figure2
