### ISSUE TITLE
Resampling methods: removing plots

### ISSUE THREAD

**Issue by Viktor-Onyshchenko** [fmsabatini/sPlotOpen_Manuscript#64]
1. Why did you remove wetland and anthropogenic plots? I think at least it needs to be explained.
2. What is meant by the word "wetland". Criteria? Only aquatic vegetation?

**Comment by fmsabatini** [comment]
The resampling was originally done for the paper
https://www.nature.com/articles/s41559-018-0699-8

I guess they were excluded because wetland data are only consistently available for Europe, and few other well-sampled regions. 
@hbruelheide and @lenjon maybe can explain the rational better, however.

**Comment by fmsabatini** [comment]
The problem with removing plots is being discussed in issue https://github.com/fmsabatini/sPlotOpen_Manuscript/issues/64

**Comment by annakuzemko** [comment]
I also had a similar question. The manuscript should explain why these two types have been removed.

**Comment by arnste** [comment]
What was the rationale for keeping plots without coordinates when plots with location uncertainty greater than 3km were removed? How were the plots with no coordinates assigned to a grid cell?

**Comment by fmsabatini** [comment]
This is now explained at line:
https://github.com/fmsabatini/sPlotOpen_Manuscript/blame/master/content/30.Methods.md#L13
