### ISSUE TITLE
Number of plots in Open Access

### ISSUE THREAD

**Issue by Rusina-S** [fmsabatini/sPlotOpen_Manuscript#90]
I just wanted to pay your attention about the number of plots from each database in Open Access. Is it true that all custodians/co-authors are aware of the number of plots they agreed to make Open Access? I ask it because I realised that I have given consent to one number during the process but the number is different in the manuscript (Table 1).

At first, the number selected for Open Access  was 1 releve from EU-LV-001 (my approval e-mail 18 September 2018).  Than, after the start of this submission  I have got an email from Francesco that there are 77 releves. Now I see in Table 1 that there are 306 releves form Latvian database.

It is OK with me. I approved the submission already. I just wonder, probably some co-authors have no idea about the changes (if there are some in other databases, too) and they will react already too lately about their possible disagreement.

**Comment by fmsabatini** [comment]
Dear Rusina, 
your comment puzzles me, as the number of plots never changes since I started contacting all custodians. In the attachment to the email of 18 Sept 2018, it was clearly indicated we were requesting 306 relevés (i.e., 5.5% of the database).

![image](https://user-images.githubusercontent.com/51127026/99281461-d01d7780-2832-11eb-871f-7556fb7bea7f.png)

You're right, though, that I made a mistake in my email, and wrongly indicated 77 relevées. This 77 is the reference number and I copy-pasted that by mistake. Sorry about that. 
Anyways, in case somebody else spots a mismatch, please let me know
